# A basic workflow to build a flutter android package
name: CI

# Controld when the workflow will run
on:
  # Run the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
    pull_request:
      banches: [main]

    # Allows you to run this workfolw manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build job
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
        #- run: flutter analyze
      # - run: flutter test
